package com.pinkdreams.common.errors

enum class ErrorCode(val httpStatus: HttpStatus) {
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    NOT_FOUND(HttpStatus.NOT_FOUND),
    ENTITLEMENT_DENIED(HttpStatus.FORBIDDEN),
    MODERATION_BLOCKED(HttpStatus.BAD_REQUEST),
    GENERATION_FAILED(HttpStatus.BAD_GATEWAY),
    VALIDATION_FAILED(HttpStatus.UNPROCESSABLE_ENTITY),
    PERSIST_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    DELIVERY_FAILED(HttpStatus.ACCEPTED),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);
}

enum class HttpStatus(val value: Int) {
    BAD_REQUEST(400),
    UNAUTHORIZED(401),
    NOT_FOUND(404),
    FORBIDDEN(403),
    BAD_GATEWAY(502),
    UNPROCESSABLE_ENTITY(422),
    INTERNAL_SERVER_ERROR(500),
    ACCEPTED(202)
}
